### ISSUE TITLE
desktop file

### ISSUE THREAD

**Issue by mazes-80** [WdesktopX/gmrun#11]
There is a slight error in data/gmrun.desktop
desktop-file-validate data/gmrun.desktop 
data/gmrun.desktop: error: (will be fatal in the future): value "gmrun.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path
data/gmrun.desktop: hint: value item "TerminalEmulator" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: System
data/gmrun.desktop: hint: value "TerminalEmulator" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu

moving my local gentoo package to use this repository I saw this error

**Comment by wdlkmpx** [comment]
it should be fixed now, although I think the hints should be disabled or something

**Comment by wdlkmpx** [comment]
I also created https://gitlab.com/wdlkmpx/gmrun/
since it's quite easy to synchronize both repos, so commits can happen in either of them
