### ISSUE TITLE
Feature request: avoid initial text selection when launching "gmrun command" by cli

### ISSUE THREAD

**Issue by dmnmsc** [WdesktopX/gmrun#12]
Hi,

I'd like to launch different URL handlers by keyboard shortcuts, so I tried setting ` gmrun file:` command expecting to keep writing and setting my query. But `file: ` it's selected when gmrun launches and text will be replaced by everything we type.  I  would lile to have an option to avoid text selection and being able to type next to that text.

My explanation is really awful so I will post to pics

Current situation:
![image](https://user-images.githubusercontent.com/8472142/147167159-99e42e79-e92a-47db-be44-8a85e5e32f51.png)

Expected:
![image](https://user-images.githubusercontent.com/8472142/147167182-87d2cdca-58dc-4fc9-b438-e4863723f308.png)

Thank you very much for this amazing tool.

**Comment by wdlkmpx** [comment]
Ok, this can be implemented as an option or a command line param (or both)

Maybe a command line param, something like this:
`gmrun -s file:`

Or maybe:
`gmrun -ns file:` (ns = no selection)

What do you think?

**Comment by wdlkmpx** [comment]
Or maybe what  you suggest is actually the expected  behavior and gmrun should not select the the text (command) that is passed from the command line

Opinions?

**Comment by wdlkmpx** [comment]
I've come to think that behavior you suggest is actually the most suitable

So I'll make it happen without a special param or option, it just seems the most reasonable thing to do
