### ISSUE TITLE
Parallel make fails

### ISSUE THREAD

**Issue by mazes-80** [WdesktopX/gmrun#13]
At compile time there is some warning about jobserver failure:

make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.

I saw there was some changes in Makefiles recently, until now calling make -j>1 was behaving well, so the problem is surely related to those changes.

**Comment by mazes-80** [comment]
It does not fail to compile, only to use jobs. Any case n=1 now

**Comment by wdlkmpx** [comment]
Can you paste the extract commands you ran, to see if I can reproduce the issue and maybe fix it?

**Comment by wdlkmpx** [comment]
Yeah it was broken while trying to avoid excessive shell code in a make file and to make BSDmake more verbose now

I think it's fixed now, please test the latest commit

**Comment by mazes-80** [comment]
Run make -j2 any case will throw the warning.
I'm not quite sure one can use the make jobserver when the build logic is managed by subshell
You always call: @sh $(WSCRIPT) ... $(SUBDIRS)
Seen your fix while typing

**Comment by mazes-80** [comment]
> I think it's fixed now, please test the latest commit
I think you can close the issue, even untested, I looked at commit, I'm confident changes are right
