### ISSUE TITLE
Make dialog only horizontally resizeable

### ISSUE THREAD

**Issue by GreenLunar** [WdesktopX/gmrun#15]
We've no more than a mere single line.

**Comment by wdlkmpx** [comment]
I'm not able to resize the dialog.

Or do you mean the Geometry setting in gmrunrc?
https://github.com/WdesktopX/gmrun/blob/master/data/gmrunrc

I guess it can replaced by 2 options
`window_width = 450`

And `#window_position = 100x100` (commented out)

**Comment by GreenLunar** [comment]
Using Xfce desktop 
![image](https://user-images.githubusercontent.com/2053884/156907596-d1fd5252-eaf6-466e-91dd-26dc9f2f32f5.png)
