### ISSUE TITLE
gmrun segmentation fault for files with colon in their name

### ISSUE THREAD

**Issue by anark10n** [WdesktopX/gmrun#18]
The bug is as the title says. If i try opening a file that has a colon in it (escaped properly or otherwise), gmrun seg faults, the command isn't even saved to history.
On arch linux, using openbox 3, and running gmrun 1.3w. Anything else i can do or run to find out more about what's causing it?

**Comment by wdlkmpx** [comment]
Sorry for the delay, I think i fixed this issue a month ago, I just pushed the changes to the git repo, please test the latest git revision (compile and run)

":" is a special char in gmrun, it's to call URL handlers (http://, file://)

I think the issue is fixed. Please confirm..

**Comment by anark10n** [comment]
I tried it with the new fixes, and it doesn't segfault anymore but it does display this error (since i was trying to open an image file with eye of mate): 
`No prgam associated with [URL_eom /home/username/path/to/file\]`
The file name cuts off after the escape character for the colon.

**Comment by wdlkmpx** [comment]
Ok sorry for the delay, it's just that I kind of lost interest in GTK apps, but I'll fix this issues once for all and release a new version..

**Comment by wdlkmpx** [comment]
I'm sure the bug is fixed (completely)

Please test this release
https://github.com/wdlkmpx/gmrun/releases/tag/1.4w

**Comment by replabrobin** [comment]
Thanks; that seems to have fixed my issue without having to change USE_GLIB_XDG
